### ISSUE TITLE
Switch from SQLite to Postgres

### ISSUE THREAD

**Issue by lithomas1** [Team-Sudo-Code/sudocodewebsite#1]
@KentoNishi 
Can you please help change the database from SQLLite to Postgres so I can edit my database and have the changes appear on heroku? Here is the link. I am asking you to do this because Postgres is being stupid and won't install on my computer
https://medium.com/agatha-codes/painless-postgresql-django-d4f03364989

**Comment by KentoNishi** [comment]
But why do we need a database

**Comment by lithomas1** [comment]
nvm i got it
